### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by jjackson85** [kylejohnson/Patiobar#22]
When I run node index.js I get the following message, I found something on another board about editing the eventcmd but I didn't have that so I created it. When I did then I still got the same error and go a new one when I ran pianobar that said cannot start eventcmd. (Exec format error). Does anyone have any suggestions as to what could help.

Thanks

 a user connected
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/.config/pianobar/currentSong'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readCurrentSong (/home/pi/Patiobar/index.js:16:23)
    at Namespace.<anonymous> (/home/pi/Patiobar/index.js:65:2)
    at emitOne (events.js:116:13)
    at Namespace.emit (events.js:211:7)
    at Namespace.emit (/home/pi/Patiobar/node_modules/socket.io/lib/namespace.js:205:10)
    at /home/pi/Patiobar/node_modules/socket.io/lib/namespace.js:172:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by bonelifer** [comment]
In the .config/pianobar folder you need need to create three files:
ctl (which is the FIFO file)
currentSong
stationList

You'd think they'd be created in from the install.sh.

**Comment by kylejohnson** [comment]
This was likely due to #25, which is now fixed.
