### ISSUE TITLE
 Buttons on web interface do not work

### ISSUE THREAD

**Issue by jmmarino** [kylejohnson/Patiobar#9]
For some reason the buttons on the web interface do not do anything. The song info and album cover do update. Any suggestions on how I can debug this ?

**Comment by jmmarino** [comment]
Not sure if this is relevant as it is just a warning but may be clue as to what is happening 
(node:16925) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:106:12)
    at Object.fs.close (fs.js:544:20)
    at /home/pi/Patiobar/index.js:39:11
    at FSReqWrap.wrapper [as oncomplete] (fs.js:697:5)

**Comment by jmmarino** [comment]
I figured out the problem. if I ran pianobar on its own I was getting an error "File at /home/pi/Patiobar/ctl is not a fifo". I had to delete the ctl file and run the command mknod ctl p. It is now working
